logging:
    level:
        com:
            alibaba:
                nacos:
                    client:
                        config:
                            impl: warn
server:
    port: 9000
spring:
    application:
        name: auth-server
    cloud:
        nacos:
            discovery:
                namespace: public
                server-addr: 192.168.1.121:8848,192.168.1.202:8848,192.168.1.70:8848
